#ifndef THRESHOLD_BLS_H
#define THRESHOLD_BLS_H

/* Generated by `just generate-header`. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct PrivateKey PrivateKey;
typedef struct PublicKey PublicKey;
typedef struct Signature Signature;
typedef struct BlindingFactor BlindingFactor;
typedef struct KeyShare KeyShare;
typedef struct PublicPoly PublicPoly;


/**
 * A BLS12-377 Keypair
 */
typedef struct Keypair Keypair;

/**
 * FFI buffer for passing variable-length data across the C boundary.
 */
typedef struct Buffer {
  /**
   * Pointer to the data
   */
  const uint8_t *ptr;
  /**
   * Length of the data in bytes
   */
  size_t len;
} Buffer;

/**
 * Given a message and a seed, it will blind it and return the blinded message
 *
 * * message: A cleartext message which you want to blind
 * * seed: A 32 byte seed for randomness. You can get one securely via `crypto.randomBytes(32)`
 * * blinded_message_out : Pointer to the memory where the blinded message will be written to
 * * blinding_factor_out : Pointer to the object storing the blinding factor
 *
 * The `blinding_factor_out` should be saved for unblinding any
 * signatures on `blinded_message_out`. It lives in-memory.
 *
 * You should use `free_vector` to free `blinded_message_out` and `destroy_token` to destroy
 * `blinding_factor_out`.
 *
 * # Safety
 * - If the same seed is used twice, the blinded result WILL be the same
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool blind(const struct Buffer *message,
           const struct Buffer *seed,
           struct Buffer *blinded_message_out,
           BlindingFactor **blinding_factor_out);

/**
 * Given a blinded signature and a blinding_factor used for blinding, it returns the signature
 * unblinded
 *
 * * blinded_signature: A message which has been blinded or a blind signature
 * * blinding_factor: The blinding_factor used to blind the message
 * * unblinded_signature: Pointer to the memory where the unblinded signature will be written to
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool unblind(const struct Buffer *blinded_signature,
             const BlindingFactor *blinding_factor,
             struct Buffer *unblinded_signature);

/**
 * Verifies the signature after it has been unblinded. Users will call this on the
 * threshold signature against the full public key
 *
 * * public_key: The public key used to sign the message
 * * message: The message which was signed
 * * signature: The signature which was produced on the message
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool verify(const PublicKey *public_key,
            const struct Buffer *message,
            const struct Buffer *signature);

/**
 * Signs the message with the provided private key and returns the signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool sign(const PrivateKey *private_key, const struct Buffer *message, struct Buffer *signature);

/**
 * Signs a *blinded* message with the provided private key and returns the signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool sign_blinded_message(const PrivateKey *private_key,
                          const struct Buffer *message,
                          struct Buffer *signature);

/**
 * Signs the message with the provided **share** of the private key and returns the **partial**
 * signature.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_sign(const KeyShare *share, const struct Buffer *message, struct Buffer *signature);

/**
 * Signs a *blinded* message with the provided *share* of the private key and returns the
 * *partial blind* signature.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_sign_blinded_message(const KeyShare *share,
                                  const struct Buffer *blinded_message,
                                  struct Buffer *signature);

/**
 * Verifies a partial signature against the public key corresponding to the secret shared
 * polynomial.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_verify(const PublicPoly *polynomial,
                    const struct Buffer *blinded_message,
                    const struct Buffer *signature);

/**
 * Verifies a partial *blinded* signature against the public key corresponding to the secret shared
 * polynomial.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_verify_blind_signature(const PublicPoly *polynomial,
                                    const struct Buffer *blinded_message,
                                    const struct Buffer *signature);

/**
 * Combines a flattened vector of partial signatures to a single threshold signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - This function does not check if the signatures are valid!
 *
 * Returns true if successful, otherwise false.
 */
bool combine(size_t threshold, const struct Buffer *signatures, struct Buffer *asig);

/**
 * Deserializes a public key from the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_pubkey(const uint8_t *pubkey_buf, PublicKey **pubkey);

/**
 * Deserializes a private key from the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_privkey(const uint8_t *privkey_buf, PrivateKey **privkey);

/**
 * Deserializes a signature from the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_sig(const uint8_t *sig_buf, Signature **sig);

/**
 * Serializes a public key to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_pubkey(const PublicKey *pubkey, uint8_t **pubkey_buf);

/**
 * Serializes a private key to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_privkey(const PrivateKey *privkey, uint8_t **privkey_buf);

/**
 * Serializes a signature to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_sig(const Signature *sig, uint8_t **sig_buf);

/**
 * Frees the memory allocated for the blinding factor
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void destroy_token(BlindingFactor *token);

/**
 * Frees the memory allocated for the keypair helper
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void destroy_keypair(struct Keypair *keypair);

/**
 * Frees the memory allocated for a private key
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void destroy_privkey(PrivateKey *private_key);

/**
 * Frees the memory allocated for a vector
 *
 * Takes a const pointer so that a caller can pass `Buffer::ptr` straight back
 * without casting away the qualifier to free its own buffer.
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void free_vector(const uint8_t *bytes, size_t len);

/**
 * Frees the memory allocated for a public key
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void destroy_pubkey(PublicKey *public_key);

/**
 * Frees the memory allocated for a signature
 *
 * # Safety
 *
 * The pointer must point to a valid instance of the data type
 */
void destroy_sig(Signature *signature);

/**
 * Generates a single private key from the provided seed.
 *
 * The return value should be destroyed with `destroy_keypair`.
 *
 * # Safety
 *
 * The seed MUST be at least 32 bytes long
 */
void keygen(const struct Buffer *seed, struct Keypair **keypair);

/**
 * Gets a pointer to the public key corresponding to the provided `KeyPair` pointer
 *
 * # Safety
 * The provided pointer will be dereferenced, so there must be valid data beneath it
 */
const PublicKey *public_key_ptr(const struct Keypair *keypair);

/**
 * Gets a pointer to the private key corresponding to the provided `KeyPair` pointer
 *
 * # Safety
 * The provided pointer will be dereferenced, so there must be valid data beneath it
 */
const PrivateKey *private_key_ptr(const struct Keypair *keypair);

#endif  /* THRESHOLD_BLS_H */
