#ifndef THRESHOLD_BLS_H
#define THRESHOLD_BLS_H

/* Generated by `just generate-header`. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct PrivateKey PrivateKey;
typedef struct PublicKey PublicKey;
typedef struct Signature Signature;
typedef struct BlindingFactor BlindingFactor;


#define PUBKEY_LEN 96

#define PRIVKEY_LEN 32

/**
 * Bytes of seed the entry points that draw randomness require. It is the whole
 * state of the RNG they seed, so a shorter seed is refused rather than padded.
 */
#define SEED_LEN 32

/**
 * Bytes bincode prepends to a serialized sequence as its length prefix.
 */
#define VEC_LENGTH 8

/**
 * Bytes in a serialized signature, compressed G1.
 */
#define SIGNATURE_LEN 48

/**
 * Bytes in a share index, spelled as a literal because cbindgen evaluates
 * these expressions itself and cannot call `size_of`. The assertion below
 * keeps it tied to `Idx`.
 */
#define IDX_LEN 4

/**
 * Bytes in one serialized partial signature. `combine` splits its flattened
 * input into chunks of this size, so a caller has to build that input to
 * match.
 */
#define PARTIAL_SIG_LENGTH ((VEC_LENGTH + SIGNATURE_LEN) + IDX_LEN)

/**
 * A BLS12-377 Keypair
 */
typedef struct Keypair Keypair;

/**
 * FFI buffer for passing variable-length data across the C boundary.
 */
typedef struct Buffer {
  /**
   * Pointer to the data
   */
  const uint8_t *ptr;
  /**
   * Length of the data in bytes
   */
  size_t len;
} Buffer;

/**
 * Given a message and a seed, it will blind it and return the blinded message
 *
 * * message: A cleartext message which you want to blind
 * * seed: A `SEED_LEN` byte seed for randomness. You can get one securely via
 *   `crypto.randomBytes(32)`
 * * blinded_message_out : Pointer to the memory where the blinded message will be written to
 * * blinding_factor_out : Pointer to the object storing the blinding factor
 *
 * The `blinding_factor_out` should be saved for unblinding any
 * signatures on `blinded_message_out`. It lives in-memory.
 *
 * You should use `free_vector` to free `blinded_message_out` and `destroy_token` to destroy
 * `blinding_factor_out`.
 *
 * # Safety
 * - If the same seed is used twice, the blinded result WILL be the same
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the seed is shorter than `SEED_LEN` bytes, the function will return false
 * - If the message cannot be blinded, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool blind(const struct Buffer *message,
           const struct Buffer *seed,
           struct Buffer *blinded_message_out,
           BlindingFactor **blinding_factor_out);

/**
 * Given a blinded signature and a blinding_factor used for blinding, it returns the signature
 * unblinded
 *
 * * blinded_signature: A message which has been blinded or a blind signature
 * * blinding_factor: The blinding_factor used to blind the message
 * * unblinded_signature: Pointer to the memory where the unblinded signature will be written to
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool unblind(const struct Buffer *blinded_signature,
             const BlindingFactor *blinding_factor,
             struct Buffer *unblinded_signature);

/**
 * Verifies the signature after it has been unblinded. Users will call this on the
 * threshold signature against the full public key
 *
 * * public_key: The public key used to sign the message
 * * message: The message which was signed
 * * signature: The signature which was produced on the message
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool verify(const PublicKey *public_key,
            const struct Buffer *message,
            const struct Buffer *signature);

/**
 * Signs the message with the provided private key and returns the signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool sign(const PrivateKey *private_key, const struct Buffer *message, struct Buffer *signature);

/**
 * Signs a *blinded* message with the provided private key and returns the signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool sign_blinded_message(const PrivateKey *private_key,
                          const struct Buffer *message,
                          struct Buffer *signature);

/**
 * Signs the message with the provided **share** of the private key and returns the **partial**
 * signature.
 *
 * * share: The serialized share of the private key, as the holder received it from key
 *   generation
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_sign(const struct Buffer *share,
                  const struct Buffer *message,
                  struct Buffer *signature);

/**
 * Signs a *blinded* message with the provided *share* of the private key and returns the
 * *partial blind* signature.
 *
 * * share: The serialized share of the private key, as the holder received it from key
 *   generation
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_sign_blinded_message(const struct Buffer *share,
                                  const struct Buffer *blinded_message,
                                  struct Buffer *signature);

/**
 * Verifies a partial signature against the public key corresponding to the secret shared
 * polynomial.
 *
 * * polynomial: The serialized public commitment polynomial from key generation. It carries
 *   its own length, so a separate length argument is not needed.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_verify(const struct Buffer *polynomial,
                    const struct Buffer *blinded_message,
                    const struct Buffer *signature);

/**
 * Verifies a partial *blinded* signature against the public key corresponding to the secret shared
 * polynomial.
 *
 * * polynomial: The serialized public commitment polynomial from key generation. It carries
 *   its own length, so a separate length argument is not needed.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool partial_verify_blind_signature(const struct Buffer *polynomial,
                                    const struct Buffer *blinded_message,
                                    const struct Buffer *signature);

/**
 * Combines a flattened vector of partial signatures to a single threshold signature
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the flattened buffer is not a whole number of `PARTIAL_SIG_LENGTH` chunks, the function
 *   will return false
 * - This function does not check if the signatures are valid!
 *
 * Returns true if successful, otherwise false.
 */
bool combine(size_t threshold, const struct Buffer *signatures, struct Buffer *asig);

/**
 * Deserializes a public key from the provided buffer
 *
 * * pubkey_buf: A buffer of exactly `PUBKEY_LEN` bytes
 * * pubkey: Pointer to the memory where the public key handle will be written to
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the buffer does not hold exactly `PUBKEY_LEN` bytes, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_pubkey(const struct Buffer *pubkey_buf, PublicKey **pubkey);

/**
 * Deserializes a private key from the provided buffer
 *
 * * privkey_buf: A buffer of exactly `PRIVKEY_LEN` bytes
 * * privkey: Pointer to the memory where the private key handle will be written to
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the buffer does not hold exactly `PRIVKEY_LEN` bytes, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_privkey(const struct Buffer *privkey_buf, PrivateKey **privkey);

/**
 * Deserializes a signature from the provided buffer
 *
 * * sig_buf: A buffer of exactly `SIGNATURE_LEN` bytes
 * * sig: Pointer to the memory where the signature handle will be written to
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the buffer does not hold exactly `SIGNATURE_LEN` bytes, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool deserialize_sig(const struct Buffer *sig_buf, Signature **sig);

/**
 * Serializes a public key to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_pubkey(const PublicKey *pubkey, uint8_t **pubkey_buf);

/**
 * Serializes a private key to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_privkey(const PrivateKey *privkey, uint8_t **privkey_buf);

/**
 * Serializes a signature to the provided buffer
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool serialize_sig(const Signature *sig, uint8_t **sig_buf);

/**
 * Frees the memory allocated for the blinding factor
 *
 * # Safety
 *
 * The pointer must be NULL, or point to a valid instance of the data type that
 * has not already been freed. Freeing a pointer twice corrupts the heap; NULL
 * does nothing.
 */
void destroy_token(BlindingFactor *token);

/**
 * Frees the memory allocated for the keypair helper
 *
 * This also frees the keys behind `public_key_ptr` and `private_key_ptr`, which
 * borrow from the keypair rather than owning their memory.
 *
 * # Safety
 *
 * The pointer must be NULL, or point to a valid instance of the data type that
 * has not already been freed. Freeing a pointer twice corrupts the heap; NULL
 * does nothing.
 */
void destroy_keypair(struct Keypair *keypair);

/**
 * Frees the memory allocated for a private key
 *
 * # Safety
 *
 * The pointer must be NULL, or come from `deserialize_privkey` and not have
 * been freed already. In particular it must not come from `private_key_ptr`,
 * which borrows from a keypair instead of allocating. Freeing a pointer twice
 * corrupts the heap; NULL does nothing.
 */
void destroy_privkey(PrivateKey *private_key);

/**
 * Frees the memory allocated for a vector
 *
 * Takes a const pointer so that a caller can pass `Buffer::ptr` straight back
 * without casting away the qualifier to free its own buffer.
 *
 * # Safety
 *
 * The pointer must be NULL, or be one this library handed out together with
 * the exact length it reported for it: the allocation is reconstructed from
 * the two, so a different length frees a different allocation. Freeing a
 * pointer twice corrupts the heap; NULL does nothing.
 */
void free_vector(const uint8_t *bytes, size_t len);

/**
 * Frees the memory allocated for a public key
 *
 * # Safety
 *
 * The pointer must be NULL, or come from `deserialize_pubkey` and not have
 * been freed already. In particular it must not come from `public_key_ptr`,
 * which borrows from a keypair instead of allocating. Freeing a pointer twice
 * corrupts the heap; NULL does nothing.
 */
void destroy_pubkey(PublicKey *public_key);

/**
 * Frees the memory allocated for a signature
 *
 * # Safety
 *
 * The pointer must be NULL, or point to a valid instance of the data type that
 * has not already been freed. Freeing a pointer twice corrupts the heap; NULL
 * does nothing.
 */
void destroy_sig(Signature *signature);

/**
 * Generates a single private key from the provided seed.
 *
 * The return value should be destroyed with `destroy_keypair`.
 *
 * # Safety
 * - **This function will dereference the provided pointers. If any invalid pointers are passed
 *   then the software will crash**.
 * - If NULL pointers are passed, the function will return false
 * - If the seed is shorter than `SEED_LEN` bytes, the function will return false
 *
 * Returns true if successful, otherwise false.
 */
bool keygen(const struct Buffer *seed, struct Keypair **keypair);

/**
 * Gets a pointer to the public key corresponding to the provided `KeyPair` pointer
 *
 * The key is **borrowed from the keypair**, not a separate allocation: it stays
 * valid until `destroy_keypair` and must never be passed to `destroy_pubkey`,
 * which would free memory that was never allocated on its own and leave
 * `destroy_keypair` to free it a second time.
 *
 * # Safety
 * The provided pointer will be dereferenced, so there must be valid data beneath it.
 * Returns NULL if a NULL keypair is passed.
 */
const PublicKey *public_key_ptr(const struct Keypair *keypair);

/**
 * Gets a pointer to the private key corresponding to the provided `KeyPair` pointer
 *
 * The key is **borrowed from the keypair**, not a separate allocation: it stays
 * valid until `destroy_keypair` and must never be passed to `destroy_privkey`,
 * which would free memory that was never allocated on its own and leave
 * `destroy_keypair` to free it a second time.
 *
 * # Safety
 * The provided pointer will be dereferenced, so there must be valid data beneath it.
 * Returns NULL if a NULL keypair is passed.
 */
const PrivateKey *private_key_ptr(const struct Keypair *keypair);

#endif  /* THRESHOLD_BLS_H */
