name: Test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Check formatting and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Run tests
        run: cargo test
